### ISSUE TITLE
发送一条指令，不停接收串口数据，直至发送停止指令有考虑过吗？

### ISSUE THREAD

**Issue by zhourenjun** [zhouhuandev/SerialPortKit#1]

**Comment by zhouhuandev** [comment]
目前暂时不考虑读取线程是否停止问题。很多情况下，涉及到串口的，也会涉及到心跳检测，与此同时，发送操作命令较为频繁，若是频繁的关闭与开启，会有情况造成部分的数据会丢失而导致无法正常的处理回调结果，与此同时，也会给CPU增加压力而导致系统资源耗尽的情况。

**Comment by zhouhuandev** [comment]
目前暂时不考虑读取线程是否停止问题。很多情况下，涉及到串口的，也会涉及到心跳检测，与此同时，发送操作命令较为频繁，若是频繁的关闭与开启，会有情况造成部分的数据会丢失而导致无法正常的处理回调结果，与此同时，也会给CPU增加压力而导致系统资源耗尽的情况。

**Comment by zhouhuandev** [comment]
> _未提供说明。_

目前暂时不考虑读取线程是否停止问题。很多情况下，涉及到串口的，也会涉及到心跳检测，与此同时，发送操作命令较为频繁，若是频繁的关闭与开启，会有情况造成部分的数据会丢失而导致无法正常的处理回调结果，与此同时，也会给CPU增加压力而导致系统资源耗尽的情况。
