### ISSUE TITLE
数据不正确？

### ISSUE THREAD

**Issue by Linnnnnn** [zhouhuandev/SerialPortKit#12]
请问为什么我用友善串口助手，波特率：9600 发送 AA BB CC DD
然后安卓端走统一数据回调收到不是完整的,分开两次了
eg1: AA
        BB CC DD
eg2: AA BB
       CC DD

**Comment by zhouhuandev** [comment]
这个应该是未检测到数据，然后把收到的数据给传回来了。

**Comment by zhouhuandev** [comment]
> 请问为什么我用友善串口助手，波特率：9600 发送 AA BB CC DD 然后安卓端走统一数据回调收到不是完整的,分开两次了 eg1: AA BB CC DD eg2: AA BB CC DD

这个应该是未检测到数据，然后把收到的数据给传回来了。
