### ISSUE TITLE
接收的数据偶发丢失的问题

### ISSUE THREAD

**Issue by smin9** [zhouhuandev/SerialPortKit#13]
这种要怎么排查是硬件的问题，还是软件的问题？？

**Comment by zhouhuandev** [comment]
> 这种要怎么排查是硬件的问题，还是软件的问题？？

通讯都是不可靠的，一般会有重传等检查机制，可以通过串口助手或者日志进行辅助排查数据信息。也有可能是下位机数据没有发送正确导致，导致因素需要具体排查而定。
