### ISSUE TITLE
发送或接收超时

### ISSUE THREAD

**Issue by Black-Knights** [zhouhuandev/SerialPortKit#14]
向模块发送这组数据时，提示发送或接收超时；
byteArrayOf(0xF5.toByte(),0x0C.toByte(),0x00.toByte()
                ,0x00.toByte(),0x00.toByte(),0x00.toByte(),0x0C.toByte(),0xF5.toByte()）
用串口助手向模块发送这组数据，能正常收到应答信息。
请问这个问题可能出在哪里？

**Comment by zhouhuandev** [comment]
> 向模块发送这组数据时，提示发送或接收超时； byteArrayOf(0xF5.toByte(),0x0C.toByte(),0x00.toByte() ,0x00.toByte(),0x00.toByte(),0x00.toByte(),0x0C.toByte(),0xF5.toByte()） 用串口助手向模块发送这组数据，能正常收到应答信息。 请问这个问题可能出在哪里？

**Comment by zhouhuandev** [comment]
> 向模块发送这组数据时，提示发送或接收超时； byteArrayOf(0xF5.toByte(),0x0C.toByte(),0x00.toByte() ,0x00.toByte(),0x00.toByte(),0x00.toByte(),0x0C.toByte(),0xF5.toByte()） 用串口助手向模块发送这组数据，能正常收到应答信息。 请问这个问题可能出在哪里？

请问这组数据是向哪里发送的，是指App发送至下位机吗？还是说串口助手发送至下位机？

**Comment by Black-Knights** [comment]
App发送至下位机时提示发送或接收超时；串口助手发送至下位机，下位机有正常应答

**Comment by zhouhuandev** [comment]
> App发送至下位机时提示发送或接收超时；串口助手发送至下位机，下位机有正常应答

你可以考虑接入源码，在发送的地方debug下，看看发送的指令是否到达了下位机。

BaseSerialPortTask#run()方法中是否正常的执行写入了数据。

**Comment by Black-Knights** [comment]
正常写入数据了，也发现自己问题在哪里了，感谢回复
