### ISSUE TITLE
请问ContextProvider.appContext如何拿到?

### ISSUE THREAD

**Issue by lm11000** [zhouhuandev/SerialPortKit#15]
库里面没有这个类.kt 不是特别熟,不知道如何传递过来 application 对象了

**Comment by zhouhuandev** [comment]
> 库里面没有这个类.kt 不是特别熟,不知道如何传递过来 application 对象了

通过 ContentProvider 拿到的Application，ContentProvider 初始化比 Application 要早，可以更早拿到 Application
