### ISSUE TITLE
core包下有个问题

### ISSUE THREAD

**Issue by aipper** [zhouhuandev/SerialPortKit#16]
SerialPortFinder类的52号 split(" +") 应该为  split(" +".toRegex())

**Comment by zhouhuandev** [comment]
> SerialPortFinder类的52号 split(" +") 应该为 split(" +".toRegex())

感谢您提供解决方案，分割字符串的方式有较多中，项目中使用的是直接字符串分割方式，您提供的为正则分割方式，两者均可满足需求，可以自行选择更合适的工具类进行操作。
