### ISSUE TITLE
关于Sender

### ISSUE THREAD

**Issue by thisdcw** [zhouhuandev/SerialPortKit#18]
我想问一下那个Sender是在哪个包下的,为什么我没找到,还是说是自定义的,如果是自定义的话,可以给我举个例子吗,谢谢了

**Comment by zhouhuandev** [comment]
您好，针对您的问题很高兴为你解答：

1. Sender 所在包位置：serial-port-kit-manage 模块中 com.serial.port.kit.manage.sender 包下面
2. AdapterSender 为 Sender 默认实现
3. Sender 核心是为了管理不同类型的命令池进行发送。

**Comment by thisdcw** [comment]
<img width="399" alt="image" src="https://github.com/zhouhuandev/SerialPortKit/assets/75626462/06b0d510-b287-43d0-9b9c-04c30b658723">
没有找到呀，是不是1.06移除了呀，要自定义

**Comment by zhouhuandev** [comment]
实在抱歉，给您错误的引导。Sender 需要自定义，您可以参数 simple-app 模块下面的 com.serial.port.kit.manage.sender.Sender 实现

￼
