### ISSUE TITLE
can not Support android 4.4?

### ISSUE THREAD

**Issue by 823546371** [zhouhuandev/SerialPortKit#2]
can not Support android 4.4?

**Comment by zhouhuandev** [comment]
目前 minSdk = 21 ，建议您可以下载源码自行降低版本作为lib库使用

**Comment by zhouhuandev** [comment]
> can not Support android 4.4?

目前 minSdk = 21 ，建议您可以下载源码自行降低版本作为lib库使用

**Comment by zhouhuandev** [comment]
> can not Support android 4.4?

最新的 1.0.2 版本已经兼容至 minSdk = 16
