### ISSUE TITLE
接收数据不全

### ISSUE THREAD

**Issue by hike2008** [zhouhuandev/SerialPortKit#20]
使用默认的processData，回调的实际数据不全，只有32字节

**Comment by zhouhuandev** [comment]
> 使用默认的processData，回调的实际数据不全，只有32字节

hi，你初始化的时候使用的什么配置可以发出来看一下吗？是否是阻塞式的方式进行读取的数据？

**Comment by hike2008** [comment]
反馈一下：是数据解析问题，需要根据项目协议，自己实现一下解析和封装逻辑。

感谢~
