### ISSUE TITLE
串口指令能正常发送，但是接收不到串口返回数据，使用串口调试工具是可以正常收发的

### ISSUE THREAD

**Issue by LuXiaoQiang** [zhouhuandev/SerialPortKit#21]
通过addDataPickListener来接收串口返回的心跳包数据，突然出现接收不到串口数据，往下位机发送指令消息可以正常发送，但是接收不到应答数据

**Comment by zhouhuandev** [comment]
> 通过addDataPickListener来接收串口返回的心跳包数据，突然出现接收不到串口数据，往下位机发送指令消息可以正常发送，但是接收不到应答数据

建议可以考虑在接收数据的地方做一层日志一步步的分析，是否有读取到下位机回传的数据哦！
