### ISSUE TITLE
su path

### ISSUE THREAD

**Issue by hgkui** [zhouhuandev/SerialPortKit#4]
可以对外公开个方法用来设置 su path。   ‘/system/bin/su’和 “/system/xbin/su”

**Comment by zhouhuandev** [comment]
> 

你为什么会用到 xbin ?

**Comment by hgkui** [comment]
有些设备的su文件是在/system/xbin目录下

**Comment by zhouhuandev** [comment]
> 有些设备的su文件是在/system/xbin目录下

已在配置文件中支持可切换 su 文件

配置方式如下：

`
SerialPortKit.newBuilder(ContextProvider.appContext)
 // 提权 su shell 切换
.setCmdSuShell(SerialPort.CMD_BIN_SU_SHELL)
`
