### ISSUE TITLE
SerialPortManager

### ISSUE THREAD

**Issue by pzb1834** [zhouhuandev/SerialPortKit#5]
导入依赖后找不到这个SerialPortManager类，是还需要导入android-serialport库吗

**Comment by zhouhuandev** [comment]
> 

![image](https://user-images.githubusercontent.com/39424623/173794499-4a94d024-8a8f-41cd-8202-fd31d6fd4ec8.png)
请确保这个类库已经加载成功了
可以根据 README.md 文件中提示导入方式进行全部导入。
现在版本为 `SNAPSHOT` 版本，每天都会进行拉取最新版本内容。

**Comment by ALuoBo** [comment]
解决方法：
在 Android Studio Chipmunk  的 settings.gradle 中 设置：
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name 'maven-snapshot'
            url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}
```

**Comment by zhouhuandev** [comment]
> 解决方法： 在 Android Studio Chipmunk 的 settings.gradle 中 设置：
> 
> ```
> dependencyResolutionManagement {
>     repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
>     repositories {
>         google()
>         mavenCentral()
>         maven {
>             name 'maven-snapshot'
>             url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
>         }
>     }
> }
> ```

OK，由于你使用的IDE版本为 Android Studio Chipmunk ，AGP 为 7.0， 这样子的话，就需要在 'setting. gradle' 中配置依赖库的仓库位置。

我将关闭当前 Issues。

**Comment by zhouhuandev** [comment]
> 解决方法： 在 Android Studio Chipmunk 的 settings.gradle 中 设置：
> 
> ```
> dependencyResolutionManagement {
>     repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
>     repositories {
>         google()
>         mavenCentral()
>         maven {
>             name 'maven-snapshot'
>             url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
>         }
>     }
> }
> ```

OK，由于你使用的IDE版本为 Android Studio Chipmunk ，AGP 为 7.0， 这样子的话，就需要在 'setting. gradle' 中配置依赖库的仓库位置。

我将关闭当前 Issues。
