### ISSUE TITLE
OnDataReceiverListener::onTimeOut cannot work for me

### ISSUE THREAD

**Issue by Yorkzero** [zhouhuandev/SerialPortKit#6]
感谢您的开发工作，我在使用过程中遇到了以下问题：

根据README.md，允许自定义接收时长`WrapSendData::waitOutTime`，于是我进行了以下的二次封装：

```kotlin
fun sendData(byteArray: ByteArray, cbDuration: Int = 1000, cb: SerialSendCallback) {
    if (!isSerialOpen) {
        Log.e(TAG, "sendData: please open the port!")
        return
    }

    val ret = SerialPortHelper.portManager.send(WrapSendData(byteArray, waitOutTime = cbDuration, receiveMaxCount = 1),
        object : OnDataReceiverListener {
            override fun onFailed(wrapSendData: WrapSendData, msg: String) {
                Log.d(TAG, "onFailed: ")
            }

            override fun onSuccess(data: WrapReceiverData) {
                Log.d(
                    TAG,
                    "onSuccess: receive data >>> ${TypeConversion.bytes2HexString(data.data)} <<<" +
                            "\n duration >>> ${data.duration} <<<"
                )
                cb(data.data, data.size)    //handle with business
            }

            override fun onTimeOut() {
                Log.e(
                    TAG,
                    "onTimeOut: send data >>> ${TypeConversion.bytes2HexString(byteArray)} <<< timeout."
                )
            }

        })
    if (ret) {
        Log.d(TAG, "sendData: >>> ${TypeConversion.bytes2HexString(byteArray)} <<< success!")
    } else {
        Log.d(TAG, "sendData: >>> ${TypeConversion.bytes2HexString(byteArray)} <<< failed!")
    }
}
```

> 我期望的结果是发送后500ms超时将会走到**onTimeOut()**，进行了以下的调用：

```kotlin
val arr = byteArrayOf(1, 0xc8.toByte(), 0, 6,
    0xCF.toByte(), 0xAA.toByte(), 0xBB.toByte())
SerialUtil.sendData(arr, 500) {data, size ->
    //TODO
}
```

但是log结果是这样的：

```
2022-06-15 16:53:52.088 30497-30497/com.makelocks.meshapp D/SerialUtil: sendData: >>> 01 C8 00 06 CF AA BB  <<< success!
2022-06-15 16:53:52.967 30497-30553/com.makelocks.meshapp D/SerialUtil: onSuccess: receive data >>> 02 C8 00 06 CC  <<<
     duration >>> 873 <<<
```

没有发生超时回调，这让我十分困惑，于是我尝试发送错误的帧：

```
2022-06-15 17:13:15.525 3687-3687/com.makelocks.meshapp D/SerialUtil: sendData: >>> 01 01 C8 00 06 CF AA BB  <<< success!
2022-06-15 17:13:20.841 3687-3687/com.makelocks.meshapp D/SerialUtil: sendData: >>> 01 01 C8 00 06 CF AA BB  <<< success!
```

两次发送时间间隔5s，均未进入超时回调，但下位机能够接收到错误的帧。

我还尝试了本库demo，也是相同的情况，请问这是什么原因造成的？

**Comment by zhouhuandev** [comment]
> ```kotlin
> duration
> ```

请您可以检查 SerialPortHelper#checkTimeOutTask 中是否获取到锁，且进行现有任务进行有效的检查更新。

当前方法是通过 SerialReadThread#run 读取数据线程进行调用，间隔为 1ms ，你可以通过debug等手段，查看是否可以正常的进行收集无效 task ，麻烦调试过后告知一声结果如何，有疑问的话，可以加我微信好友，联系方式在 BaseDemo 开源库中，我有空的话，协助你进行调试。

**Comment by Yorkzero** [comment]
目前debug发现的现象是`SerialReadThread::Run()`似乎在`InputStream::read(Byte[])`处发生了阻塞，每次有数据上报时阻塞恢复，随后执行一次`checkTimeOutTask`

因为我是第一次使用串口，所以不太清楚串口I/O流的逻辑，串口是否可以像Socket那样抛出TimeoutException？还是我的设备问题？你的设备可以检测出超时吗？

**Comment by zhouhuandev** [comment]
> 目前debug发现的现象是`SerialReadThread::Run()`似乎在`InputStream::read(Byte[])`处发生了阻塞，每次有数据上报时阻塞恢复，随后执行一次`checkTimeOutTask`
> 
> 因为我是第一次使用串口，所以不太清楚串口I/O流的逻辑，串口是否可以像Socket那样抛出TimeoutException？还是我的设备问题？你的设备可以检测出超时吗？

你使用的是自定义协议解析，还是默认读取数据解析？在 `SerialPortHelper::sendMessage` 中是获取到锁资源的，因为牵扯到无效资源清理。我这边暂时没有设备进行调试你说的发生的现象，如果可以的话，你在 `debug` 的时候可以在把检测超时任务前移至 `InputStream::read(Byte[])` 之前看下是否可以解决问题。可以的话，你也可以提供 pr。

串口I/O流的操作与Socket在底层交流逻辑层面，几乎相同。但是Socket是通过上层封装进行处理的内容。也可以借鉴 `TimeoutException` 思想进行处理。

**Comment by zhouhuandev** [comment]
merged  [perf(SerialReadThread#Run): Non-blocking reception #8](https://github.com/zhouhuandev/SerialPortKit/pull/8)

**Comment by Yorkzero** [comment]
#8 
1.0.5-SNAPSHOT 20byte的数据帧收发测试功能正常，大量数据的收发暂时没有条件测试

**Comment by zhouhuandev** [comment]
> #8 1.0.5-SNAPSHOT 20byte的数据帧收发测试功能正常，大量数据的收发暂时没有条件测试

在日常的串口通讯开发的场景中，下位机上发数据应该都不会过大。等待有机会的时候再进行测试大数据的读取。
